### ISSUE TITLE
UnityActivateLicenseTask is adding project path making task take ~5m

### ISSUE THREAD

**Issue by robtraynor** [Dinomite-Studios/unity-azure-pipelines-tasks#233]
Passing the project path causes an import of assets which can take a while. This was a regresssion in #226 to fix #225, suggestion is to omit the unityProjectPath if it is not set.

**Comment by FejZa** [comment]
You are right. This has been addressed in the recent release. While this did cause asset import and increased time for this task to complete on the other hand it would speed up the build task because it did not have to perform asset import at that point.

Still I believe the activation task should not pass a project.
