### ISSUE TITLE
Migrate from Azure Pipelines to GitHub actions

### ISSUE THREAD

**Issue by bdovaz** [Dinomite-Studios/unity-azure-pipelines-tasks#271]
# Unity Tools for Azure DevOps - Feature Request

## Please describe your feature request

Currently the CI/CD [is in Azure Pipelines](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/blob/main/azure-pipelines.yml) and has the problem that we don't have access and it gives 401 errors which makes it difficult to review our own or other PRs.

The pipeline is simple enough to migrate it from Azure Pipelines to GitHub actions without much difficulty which makes everything much more integrated into the GitHub ecosystem.

In the other repository I already did it myself back in the day: 

https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks-lib/pull/5

https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks-lib/pull/9

**Comment by FejZa** [comment]
It used to be on GitHub but I moved it back to DevOps some time ago since that is where I felt "at home".
We can move it to GitHub as part of https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/issues/272 I guess. But first I need to get some more PRs in for another release I want to do adressing recent changes.
